---
--- Generated by Luanalysis
--- Created by xdu.
--- DateTime: 2024/8/28 15:37
---

wrk.method="POST"
wrk.headers["Content-Type"] = "application/json"
-- 这个要改为你的注册的数据
wrk.body='{"email":"12347@qq.com", "password": "hello@world123"}'