---
--- Generated by Luanalysis
--- Created by xdu.
--- DateTime: 2024/8/28 21:12
---
---
--- phone_code:login:152xxxxxxxx
local key=KEYS[1]
--- phone_code:login:152xxxxxxxx:cnt 验证次数
local cntKey=key..":cnt"
--- 验证码 123456
local val = ARGV[1]
--- 过期时间
local ttl = tonumber(redis.call("ttl", key))

if ttl == -1 then
    ---    key 存在，但是没有过期时间
    --- 系统错误，你的同事手贱，手动设置了这个 key，但是没给过期时间
    return -2
    ---    540 = 600-60 九分钟
elseif ttl == -2 or ttl < 540 then
    redis.call("set", key, val)
    redis.call("expire", key, 600)
    redis.call("set", cntKey, 3)
    redis.call("expire", cntKey, 600)
    -- 完美，符合预期
    return 0
else
    -- 发送太频繁
    return -1
end