---
--- Generated by Luanalysis
--- Created by xdu.
--- DateTime: 2024/8/28 21:38
---
local key = KEYS[1]
--- 输入的code
local expectCode = ARGV[1]
--- 获取redis缓存的code
local code =redis.call("get",key)
local cntKey= key..":cnt"
--- 获取读取次数
local cnt=tonumber(redis.call("get",cntKey))

if cnt<=0 then
    --- 已经用过了/攻击
    return -1
elseif expectCode==code then
    --- 设置code失效
    redis.call("set",cntKey,-1)
    return 0
else
    --- 输入错误，验证次数-1
    redis.call("decr", cntKey)
    return -2
end